### ISSUE TITLE
Zig head version breaks build.zig.

### ISSUE THREAD

**Issue by floooh** [kassane/sokol-d#19]
Just a heads up, I noticed in sokol-zig that the current Zig head version changed Build.LazyPath, and this also affects the build.zig script in sokol-d.

```
/Users/floh/projects/sokol-d/build.zig:61:44: error: no field named 'path' in union 'Build.LazyPath'
    lib.root_module.root_source_file = .{ .path = "src/handmade/math.zig" };
```

...I think this specific error can be fixed like:

```
lib.root_module.root_source_file = b.path("src/handmade/math.zig");
```

...the Emscripten stuff is a bit more complicated unfortunately, see my changes in sokol-zig:

https://github.com/floooh/sokol-zig/commit/27683f5c159383d286852963f7ec78f438aeae7f

**Comment by floooh** [comment]
...btw, in sokol-zig I'm updated the branch `zig-0.12.0` to the last version that worked in 0.12.0.

**Comment by floooh** [comment]
PS: those changes actually work in zig-0.12.0 too, so no harm done.

**Comment by floooh** [comment]
PS: as a temporary workaround in the sokol repo, I have pinned the Zig version in the Bindings CI pipeline to 0.12.0:

https://github.com/floooh/sokol/blob/7d348db1402f5ee3abc2be65db6b3cf9ef669e23/.github/workflows/gen_bindings.yml#L276-L278

The CI in the sokol-d repo will still break, but at least that way the bindings get properly updated for now.

**Comment by kassane** [comment]
Based on build-test #20 , maybe for now the ideal is to stick to v0.12.0, until the cached build on master bug is resolved.

**Comment by floooh** [comment]
Yeah I agree, probably better to wait a bit until zig-dev stabilizes a bit. Thanks for the CI fix!

**Comment by kassane** [comment]
According to my tests in #21, I see differential behavior between the build and cached-build by the zig toolchain.
Therefore, once the real issue has been identified, I'll attempt to come back and evaluate if the same occurs in the `0.13.0-dev` issue.
